### PR TITLE
Allow users to customize the count_words behaviour

### LINKED ISSUE #3: word cloud: consider same words in different forms, ie, nouns, adjectives...

### LINKED ISSUE #50: Preserve letter case for selected words in anno_word_cloud
Would it be within the scope of this package to add an argument to `anno_word_cloud()` which would allow to provide a list of words that should follow a specific letter case pattern? For example the example from README includes "DNA" which should be capitalized, but is lowercase ("dna") in the world cloud:

image

In a general case I find it difficult to interpret the meaning when seeing gene and protein symbols in an unfamiliar letter case. This is a slight annoyance during interpretation, but also a show stopper for publishing in some journals which might be very strict on gene/protein formatting (so one would need to manually edit the figure, which is best avoided).

In particular this line is enforcing the lowercase formatting and is not user-adjustable:

https://github.com/jokergoo/simplifyEnrichment/blob/3dbbaf52e68ba6e81bb3c2126dd15770f8d718d8/R/word_count.R#L27-L28

### LINKED ISSUE #51: Review the stopwords exclusion
After looking at the code I noticed that the stop words are filtered out automatically. This is nice! It would however be good to include this in the documentation and potentially allow to adjust the default list. Apologies if I missed a mention of this but it looks that [reference anno_word_cloud](https://jokergoo.github.io/simplifyEnrichment/reference/anno_word_cloud.html) does not mention this behaviour. Some potentially problematic exclusions are:
- "was" - there is a gene named "WAS" (producing Wiskott-Aldrich syndrome protein)
- "down" - will filter out "down" as in "down syndrome"

https://github.com/jokergoo/simplifyEnrichment/blob/92f5940c4ad278cd763b51060b5a45336f02fb81/R/word_count.R#L31-L32

The full list of `tmstopwords()` as produced by version XX of tm embedded below for convenience:

<details>

- i
- me
- my
- myself
- we
- our
- ours
- ourselves
- you
- your
- yours
- yourself
- yourselves
- he
- him
- his
- himself
- she
- her
- hers
- herself
- it
- its
- itself
- they
- them
- their
- theirs
- themselves
- what
- which
- who
- whom
- this
- that
- these
- those
- am
- is
- are
- was
- were
- be
- been
- being
- have
- has
- had
- having
- do
- does
- did
- doing
- would
- should
- could
- ought
- i'm
- you're
- he's
- she's
- it's
- we're
- they're
- i've
- you've
- we've
- they've
- i'd
- you'd
- he'd
- she'd
- we'd
- they'd
- i'll
- you'll
- he'll
- she'll
- we'll
- they'll
- isn't
- aren't
- wasn't
- weren't
- hasn't
- haven't
- hadn't
- doesn't
- don't
- didn't
- won't
- wouldn't
- shan't
- shouldn't
- can't
- cannot
- couldn't
- mustn't
- let's
- that's
- who's
- what's
- here's
- there's
- when's
- where's
- why's
- how's
- a
- an
- the
- and
- but
- if
- or
- because
- as
- until
- while
- of
- at
- by
- for
- with
- about
- against
- between
- into
- through
- during
- before
- after
- above
- below
- to
- from
- up
- down
- in
- out
- on
- off
- over
- under
- again
- further
- then
- once
- here
- there
- when
- where
- why
- how
- all
- any
- both
- each
- few
- more
- most
- other
- some
- such
- no
- nor
- not
- only
- own
- same
- so
- than
- too
- very

</details>

### LINKED ISSUE #52: Preserve whitespace for selected phrases and/or allow to include n-grams
Some phrases/terms make much more sense when analysed as a single term, for example one of my word clouds shows up "cycle" but I know that this is a combination of "cell cycle" and other cycles; I would like to single out "cell cycle" as a term that should not be split on space. It is a common practice when generating word clouds for research to specify a list of such _n_-grams that should be preserved.

On related note, it could be useful to allow to include all _n_-grams of specified length (up to specified _n_). The [FAQ section of the tm package](http://tm.r-forge.r-project.org/faq.html#Bigrams) describes that this is possible by providing a custom tokenizer:

```R
  BigramTokenizer <-
  function(x)
    unlist(lapply(ngrams(words(x), 2), paste, collapse = " "), use.names = FALSE)

  tdm <- TermDocumentMatrix(crude, control = list(tokenize = BigramTokenizer))
```

A simple solution would be to expose the `control` list as an argument that users can customize (thus providing a custom tokenizer).

### LINKED ISSUE #53: All two-letter gene/protein/metabolite names are disregarded
The `TermDocumentMatrix` by default removes all one and two letter words. I think that the one letter words are not hugely important, but there are quite a few processes name abbreviations, genes, proteins and metabolites with two-letter names used in pathway names. It would be nice to allow to preserve those. The issue arises in the following line:

https://github.com/jokergoo/simplifyEnrichment/blob/3dbbaf52e68ba6e81bb3c2126dd15770f8d718d8/R/word_count.R#L40-L41

and can be reproduced with:

```R
docs = Corpus(VectorSource(c('ER', 'PE', '333')))  # estrogen receptor, phosphatidylethanolamine, and three three
tdm = TermDocumentMatrix(docs)
v = sort(slam::row_sums(tdm), decreasing = TRUE)
print(v)
```

```
333 
  1 
```

and with:

```R
print(tdm)
```

```
<<TermDocumentMatrix (terms: 1, documents: 3)>>
Non-/sparse entries: 1/2
Sparsity           : 67%
Maximal term length: 3
Weighting          : term frequency (tf)
```

I find the `tm` documentation very sparse, but [this answer on SO](https://stackoverflow.com/a/24388735/6646912) tells us that we can fix that by passing `control=list(wordLengths=c(1,Inf)` which indeed works ok:

```R
tdm = TermDocumentMatrix(docs, control=list(wordLengths=c(1,Inf)))
v = sort(slam::row_sums(tdm), decreasing = TRUE)
print(v)
```

```
 ar  pe 333 
  1   1   1 
```

Sorry for the deluge of issues!

### PR DESCRIPTION
**Pull request by krassowski**
This is a draft proposal (early PR to get feedback) which:
- [x] fixes #50 by allowing to provide custom letter case transformation function in `transform_case` argument,
  - [ ] needs an example in vignette/documentation to show how to create a transformer that will lower case all words except for the user-provided gene names (or maybe a helper function for that?)
- [x] fixes #51 - allows to adjust the stop words by passing custom `stop_words` argument, and recommends doing so if conflicts might be a problem in the `anno_word_cloud` documentation details section
- [x] closes #52 - allows to preserve white space by providing custom tokenizer
  - [ ] needs an example in vignette/documentation to show how to create a tokenizer that will split on whitespaces except for provided set of phrases (or maybe a helper function for that?)
- [x] fixes #53 - changes the default behaviour by now counting all two letter words. One letter words are still discarded. This behaviour can be overwritten by adjusting `min_word_length` argument
- [x] closes #3; `stemming = TRUE` will replace inflected words words; for example `tm::stemDocument('signalling signaling signaled signals')` gives `signal signal signal signal`; the default `tm` stemmer, [stemDocument](https://rdrr.io/rforge/tm/man/stemDocument.html) uses Snowball stemmer which implements and improved version of Porter's stemming algorithm. 
  - [ ] add an example in vignette?
  - [ ] this requires `SnowballC` to be installed; should it become a formal dependency (`requires`), suggested dependency (`suggests`) or something that is only mentioned in the documentation?

Other changes:
- forces `tolower = FALSE` in `TermDocumentMatrix` call which should result in mino performance improvement with default settings (previously `tolower` was done twice, once in `tm_map`, and once internally by `TermDocumentMatrix`)
- allow to disable removal of numbers, removal of punctuation
- allows to provide a custom dictionary so that only selected subset of words are counted
- allows to provide a custom words transformation function

### CODE REVIEW

**Comment by krassowski** [comment]
Question: should `exclude_words` be removed from `anno_word_cloud` as it now can be passed within `count_words_param` list, or should it stay as-is for backward compatibility?

**Comment by krassowski** [comment]
I would also propose adding three helper functions (not yet committed as I would like to learn if those are in scope first):
- `term_preserving_tokenizer(preserve)` - creates a tokenizer that preserves whitespaces for specified set of phrases
- `n_gram_tokenizer(min_n, max_n)` - creates a tokenizer that returns tokens for n-grams where min_n <= n <= max_n
- `harmonize_letter_case(to=tolower, preserve=c())` - creates a function that harmonizes letter case as specified but preserves letter case for words matching the words in preserve character vector.

Draft implementation:

```R
# tokenizers.R

resolve_tokenizer = function(tokenizer) {
    if (tokenizer == 'words') {
        tokenizer = tm::scan_tokenizer
    }
    tokenizer
}

n_grams = function(sequence, n) {
    if (n <= 0) {
        stop('n must be greater than 0')
    }
    if (length(sequence) < n) {
        return(character())
    }
    indices = seq(0, n - 1)
    sapply(
        seq(1, length(sequence) - n + 1),
        function(start) {
            paste(sequence[indices + start], collapse=' ')
        }
    )
}


all_n_grams = function(sequence, min_n, max_n) {
    if (min_n > max_n) {
        stop('max_n must be greater than min_n')
    }
    unlist(
        sapply(
            seq(min_n, max_n),
            function (n) {
                n_grams(sequence, n)
            },
            simplify=FALSE
        )
    )
}

# TODO: export
# max_n- Maximal number of grams in the n-gram; if not given same as min_n.
n_gram_tokenizer = function(min_n, max_n=NULL, tokenizer='words') {
    if(is.null(max_n)) {
        max_n = min_n
    }
    tokenizer = resolve_tokenizer(tokenizer)
    final_tokenizer = function(documents) {
        documents = as.character(documents)
        unname(unlist(sapply(
            documents,
            function (document) {
                tokens = tokenizer(document)
                if (length(tokens) < min_n) {
                    return(character())
                }
                unlist(
                    lapply(
                        all_n_grams(tokens, min_n=min_n, max_n=max_n),
                        paste,
                        collapse=' '
                    ),
                    use.names=FALSE
                )
            },
            simplify=FALSE
        )))
    }
    final_tokenizer
}

# TODO: export
term_preserving_tokenizer = function(preserve, tokenizer='words') {
    tokenizer = resolve_tokenizer(tokenizer)
    final_tokenizer = function (documents) {
        documents = as.character(documents)
        unname(unlist(sapply(
          documents,
          function (document) {
              tokens = tokenizer(document)
              # TODO: only include those that actually are present in the tokens
              c(tokens, preserve)
          }
        )))
    }
}

# probably word_count.R:
harmonize_letter_case = function(to=tolower, preserve=c(), tokenizer='words') {
    tokenizer = resolve_tokenizer(tokenizer)
    harmonizer = function(words) {
        paste(
            sapply(
                tokenizer(words),
                FUN=function(word) {
                    if (word %in% preserve) {
                        return(word)
                    } else {
                        return(to(word))
                    }
                }
            ),
            collapse=' '
        )
    }
    return(harmonizer)
}
```

Draft tests:

<details>

```R
context("test test_tokenizers")

#
# n_grams
#
test_that("n_grams works correctly", {
    expect_equal(n_grams(c(), 1), character())
    expect_equal(n_grams(c('a'), 1), c('a'))
    expect_equal(n_grams(c('a', 'b'), 1), c('a', 'b'))

    expect_equal(n_grams(c(), 2), character())
    expect_equal(n_grams(c('a'), 2), character())
    expect_equal(n_grams(c('a', 'b'), 2), c('a b'))
    expect_equal(n_grams(c('a', 'b', 'c'), 2), c('a b', 'b c'))
    expect_equal(n_grams(c('a', 'b', 'c', 'd'), 2), c('a b', 'b c', 'c d'))
    expect_equal(n_grams(c('a', 'b', 'c', 'd', 'e'), 2), c('a b', 'b c', 'c d', 'd e'))

    expect_equal(n_grams(c(), 3), character())
    expect_equal(n_grams(c('a'), 3), character())
    expect_equal(n_grams(c('a', 'b'), 3), character())
    expect_equal(n_grams(c('a', 'b', 'c'), 3), c('a b c'))
    expect_equal(n_grams(c('a', 'b', 'c', 'd'), 3), c('a b c', 'b c d'))
    expect_equal(n_grams(c('a', 'b', 'c', 'd', 'e'), 3), c('a b c', 'b c d', 'c d e'))
})

#
# all_n_grams
#
test_that("all_n_grams works correctly", {
    expect_equal(all_n_grams(c('a', 'b'), min_n=1, max_n=2), c('a', 'b', 'a b'))
    expect_equal(all_n_grams(c('a', 'b', 'c'), min_n=1, max_n=2), c('a', 'b', 'c', 'a b', 'b c'))
    expect_equal(all_n_grams(c('a', 'b'), min_n=1, max_n=1), c('a', 'b'))
})

#
# n_gram_tokenizer
#
test_that("n_gram_tokenizer follows tm tokenizers API for n=1", {
    # ensure that the custom tokenizer has the same responses as the default words (scan_tokenizer) for n=1
    onegram_tokenizer = n_gram_tokenizer(1)
    expect_equal(onegram_tokenizer(''), tm::scan_tokenizer(''))
    expect_equal(onegram_tokenizer('a'), tm::scan_tokenizer('a'))
    expect_equal(onegram_tokenizer('a b c'), tm::scan_tokenizer('a b c'))
    expect_equal(onegram_tokenizer(c('a b', 'x y')), tm::scan_tokenizer(c('a b', 'x y')))
    expect_equal(onegram_tokenizer(list('a b', 'x y')), tm::scan_tokenizer(list('a b', 'x y')))
})

test_that("n_gram_tokenizer works with tm documents", {
    expect_equal(onegram_tokenizer(tm::PlainTextDocument('a b')), tm::scan_tokenizer(tm::PlainTextDocument('a b')))
})

test_that("n_gram_tokenizer works correctly for n > 1", {
    # ensure expected behaviour for n > 1
    bigram_tokenizer = n_gram_tokenizer(2)
    expect_equal(bigram_tokenizer('a b'), c('a b'))
    expect_equal(bigram_tokenizer('a b c'), c('a b', 'b c'))

    trigram_tokenizer = n_gram_tokenizer(3)
    expect_equal(trigram_tokenizer('a b'),  character())
    expect_equal(trigram_tokenizer('a b c d'),  c('a b c', 'b c d'))
    expect_equal(trigram_tokenizer(c('a b c d', 'x y z')),  c('a b c', 'b c d', 'x y z'))
})
```

</details>

**Comment by jokergoo** [comment]
Hi, Thank you for your contribution!! and sorry I forgot to reply you.

Currently the simplyEnrichment manuscript is under review (I should receive the comments from reviewers soon). I am planing to work on this in the manuscript revision.

**Comment by krassowski** [comment]
Thank you! Feel free to commit the helper tokenizers from the comments above as well. Sorry for being less responsive last few weeks - I was enjoying holiday time which meant trying to limit engaging in the open source to projects that I currently maintain ;)

I will be doing more pathway analysis in September and happily contribute fixes for other small things I may encounter.

**Comment by jokergoo** [comment]
Thank you too for all your contributions! Analyzing text is something missing or too simplified in current version. Definitely I need to improve this part. I am very new in this area (text processing, NLP) and everything is based on googling :)

Also now some functions become complicated for integrating new features. I need to think about the API of these functions to make them easier to use.

And last, enjoying your holiday time!

**Pull request merged**
